definitions:
  contact__site_page:
    weight: -50
    menu_name: footer
    parent: ''
    enabled: true
    expanded: false
  standard__front_page:
    weight: -42
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
