features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://TEDx_logo_RGB_3650-pipitea-transparant-website.png'
favicon:
  use_default: 1
custom_css: 0
