features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/tedx_pipitea_theme/logo.png
favicon:
  use_default: 1
custom_css: 0
